### ISSUE TITLE
CPP guide翻译问题

### ISSUE THREAD

**Issue by YiXiaoKezz** [zh-google-styleguide/zh-google-styleguide#171]
6.13整型中，两处将assert翻译为断言：
1." Instead, use assertions for this." 
2."Do not use an unsigned type merely to assert that a variable is non-negative."

第一处翻译为断言应该不是原文的意思吧？ 
第二处翻译为“不要仅仅为了指出一个变量非负而使用无符号类型”是否好一些？
希望能解答我的困惑，万分感谢。

**Comment by iyongliang** [comment]
最新版本：https://codiepp.github.io/styleguide/cppguide.html
You should not use the unsigned integer types such as uint32_t, unless there is a valid reason such as representing a bit pattern rather than a number, or you need defined overflow modulo 2^N.
In particular, do not use unsigned types to say a number will never be negative. Instead, use assertions for this.
不要使用 uint32_t 等无符号整型, 除非你是在表示一个位组而不是一个数值, 或是你需要定义二进制补码溢出.
尤其是不要为了指出数值永不会为负, 而使用无符号类型. 相反, 你应该使用断言来保护数据.

第一点：把参数定义成无符号并不能阻止别人传有符号数据进来，如果想明确阻止就要用断言。
第二点：我觉得下面几段论述，都是上面“如果已知整数不会太大”的前提下的讨论，跟 uint32_t 没什么关系
